<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFrameworks>net47</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <RootNamespace>LB_Mod_Installer</RootNamespace>
    <AssemblyName>LB Mod Installer</AssemblyName>
    <ApplicationIcon>Resources\DBXV2_101.ico</ApplicationIcon>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ControlzEx" Version="4.4.0" />
    <PackageReference Include="Costura.Fody" Version="6.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ini-parser-netstandard" Version="2.5.3" />
    <PackageReference Include="MahApps.Metro" Version="2.4.9" />
    <PackageReference Include="MahApps.Metro.IconPacks.MaterialLight" Version="4.11.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.19" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="1.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="YAXLib">
      <HintPath>..\DLLs\YAXLib.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Xv2CoreLib\Xv2CoreLib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\silence.hca" />
  </ItemGroup>
</Project>
