<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFrameworks>net47</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <RootNamespace>AudioCueEditor</RootNamespace>
    <AssemblyName>ACE</AssemblyName>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommonServiceLocator" Version="2.0.2" />
    <PackageReference Include="ControlzEx" Version="4.4.0" />
    <PackageReference Include="Costura.Fody" Version="6.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MvvmLightStd10" Version="5.4.1.2" />
    <PackageReference Include="MahApps.Metro" Version="2.4.9" />
    <PackageReference Include="MahApps.Metro.IconPacks.MaterialLight" Version="4.11.0" />
    <PackageReference Include="MahApps.Metro.IconPacks.Material" Version="4.11.0" />
    <PackageReference Include="MahApps.Metro.IconPacks.MaterialDesign" Version="4.11.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.19" />
    <PackageReference Include="NAudio" Version="1.9.0" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="1.1.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="AutoUpdater">
      <HintPath>..\DLLs\AutoUpdater.dll</HintPath>
    </Reference>
    <Reference Include="YAXLib">
      <HintPath>..\DLLs\YAXLib.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LB_Common\LB_Common.csproj" />
    <ProjectReference Include="..\Xv2CoreLib\Xv2CoreLib.csproj" />
  </ItemGroup>
	<!-- PresentationFramework.Aero is not automatically included with UseWPF=true, so must be manually included here -->
	<ItemGroup>
		<Reference Include="PresentationFramework.Aero" />
	</ItemGroup>
	
</Project>
