<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net47</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RootNamespace>XV2_Serializer</RootNamespace>
    <AssemblyName>XV2 Xml Serializer</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Deterministic>true</Deterministic>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Costura.Fody" Version="6.2.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Reference Include="YAXLib">
      <HintPath>..\DLLs\YAXLib.dll</HintPath>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Xv2CoreLib\Xv2CoreLib.csproj" />
  </ItemGroup>
</Project>