<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFrameworks>net47</TargetFrameworks>
    <OutputType>Library</OutputType>
    <RootNamespace>Xv2CoreLib</RootNamespace>
    <AssemblyName>Xv2CoreLib</AssemblyName>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <LangVersion>8</LangVersion>
  </PropertyGroup>
	
	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
    <LangVersion>latest</LangVersion>
	</PropertyGroup>
	
	<!-- General PackageReferences -->
  <ItemGroup>
		<PackageReference Include="FastCloner" Version="3.5.6" />
    <PackageReference Include="MvvmLightLibsStd10" Version="5.4.1.1" />
		<PackageReference Include="MahApps.Metro" Version="2.4.9" />
		<PackageReference Include="MahApps.Metro.IconPacks.Material" Version="4.11.0" />
		<PackageReference Include="MahApps.Metro.IconPacks.MaterialDesign" Version="4.11.0" />
		<PackageReference Include="MahApps.Metro.IconPacks.MaterialLight" Version="4.11.0" />
		<PackageReference Include="MIConvexHull" Version="1.1.19.1019" />
		<PackageReference Include="Microsoft.IO.RecyclableMemoryStream" Version="1.2.2" />
		<PackageReference Include="Pfim" Version="0.11.3" />
		<PackageReference Include="SharpNoise" Version="0.12.1.1" />
		<PackageReference Include="System.Numerics.Vectors" Version="4.6.1" />
		<PackageReference Include="WriteableBitmapEx" Version="1.6.11" />
	</ItemGroup>
	
	<!-- .NET 10 specific references -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net10.0-windows'">
		<Reference Include="YAXLib">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>..\..\XV2 Tools\DLLs\net10\YAXLib.dll</HintPath>
		</Reference>
		<Reference Include="CSharpImageLibrary">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>..\..\XV2 Tools\DLLs\net10\CSharpImageLibrary.dll</HintPath>
		</Reference>
	</ItemGroup>
	
	<!-- .NET Framework 4.7 specific references -->
	<ItemGroup Condition="'$(TargetFramework)' == 'net47'">
		<PackageReference Include="CSharpImageLibrary" Version="3.2.0.0" />
		<Reference Include="YAXLib">
			<SpecificVersion>False</SpecificVersion>
			<HintPath>..\..\XV2 Tools\DLLs\YAXLib.dll</HintPath>
		</Reference>
		<Reference Include="System.Half">
			<HintPath>..\DLLs\System.Half.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.CSharp" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" />
	</ItemGroup>
	
  <ItemGroup>
    <EmbeddedResource Include="Resources\silence.hca" />
    <EmbeddedResource Include="Resources\XV2P_SLOTS_STAGE.x2s" />
    <EmbeddedResource Include="Resources\XV2P_SLOTS_STAGE_LOCAL.x2s" />
    <EmbeddedResource Include="Resources\HavokConvexTemplate.hkx" />
    <EmbeddedResource Include="Resources\HavokMeshTemplate.hkx" />
    <EmbeddedResource Include="Resources\AcbFormatHelper.xml" />
    <EmbeddedResource Include="Resources\ShaderHelper.xml" />
    <EmbeddedResource Include="Resources\xv2_stage_def.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\LB_Common\LB_Common.csproj" />
  </ItemGroup>
</Project>