using System;
using System.Collections.Generic;
using YAXLib;

namespace Xv2CoreLib.SDS
{
    [YAXSerializeAs("SDS")]
    public class SDS_File
    {
        [YAXCollection(YAXCollectionSerializationTypes.RecursiveWithNoContainingElement, EachElementName = "SDSShaderProgram")]
        public List<SDSShaderProgram> ShaderPrograms { get; set; } = new List<SDSShaderProgram>();

        //Currently only loads from an XML generated by XenoXMLConverter.
        public static SDS_File LoadFromXml(string xmlPath)
        {
            YAXSerializer serializer = new YAXSerializer(typeof(SDS_File), YAXSerializationOptions.DontSerializeNullObjects);
            return(SDS_File)serializer.DeserializeFromFile(xmlPath);
        }
    }

    public class SDSShaderProgram
    {
        [YAXAttributeForClass]
        [YAXSerializeAs("name")]
        public string Name { get; set; }
        [YAXAttributeForClass]
        [YAXSerializeAs("vertexShader_name")]
        public string VertexShader { get; set; }
        [YAXAttributeForClass]
        [YAXSerializeAs("pixelShader_name")]
        public string PixelShader { get; set; }

        [YAXCollection(YAXCollectionSerializationTypes.RecursiveWithNoContainingElement, EachElementName = "SDSParameter")]
        public List<SDSParameter> Parameters { get; set; } = new List<SDSParameter>();

    }

    public class SDSParameter
    {
        [YAXAttributeForClass]
        [YAXSerializeAs("name")]
        public string Name { get; set; }
        [YAXAttributeForClass]
        [YAXSerializeAs("type")]
        public string Type { get; set; }
    }
}
