//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xv2CoreLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xv2CoreLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;AcbFormatHelperMain&gt;
        ///  &lt;Versions&gt;
        ///    &lt;String&gt;0.81.1.0&lt;/String&gt;
        ///    &lt;String&gt;0.81.8.0&lt;/String&gt;
        ///    &lt;String&gt;1.3.0.0&lt;/String&gt;
        ///    &lt;String&gt;1.6.0.0&lt;/String&gt;
        ///    &lt;String&gt;1.12.0.0&lt;/String&gt;
        ///    &lt;String&gt;1.14.0.0&lt;/String&gt;
        ///    &lt;String&gt;1.16.1.0&lt;/String&gt;
        ///    &lt;String&gt;1.21.1.0&lt;/String&gt;
        ///    &lt;String&gt;1.22.4.0&lt;/String&gt;
        ///    &lt;String&gt;1.23.1.0&lt;/String&gt;
        ///    &lt;String&gt;1.26.0.0&lt;/String&gt;
        ///    &lt;String&gt;1.27.2.0&lt;/String&gt;
        ///    &lt;String&gt;1.27.7.0&lt;/String&gt;
        ///    &lt;String&gt;1.28.2.0&lt;/String&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AcbFormatHelper {
            get {
                return ResourceManager.GetString("AcbFormatHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ShaderHelper&gt;
        ///  &lt;Shader ShaderProgram=&quot;ParticleDecal&quot;&gt;
        ///    &lt;Parameter Name=&quot;GlareCol&quot; /&gt;
        ///    &lt;Parameter Name=&quot;AlphaBlend&quot; /&gt;
        ///    &lt;Parameter Name=&quot;AlphaBlendType&quot; /&gt;
        ///    &lt;Parameter Name=&quot;ZWriteMask&quot; /&gt;
        ///    &lt;Parameter Name=&quot;LowRez&quot; /&gt;
        ///    &lt;Parameter Name=&quot;Glare&quot; /&gt;
        ///    &lt;Parameter Name=&quot;BackFace&quot; /&gt;
        ///    &lt;Parameter Name=&quot;LowRezSmoke&quot; /&gt;
        ///    &lt;Parameter Name=&quot;TwoSidedRender&quot; /&gt;
        ///    &lt;Parameter Name=&quot;AlphaTest&quot; /&gt;
        ///    &lt;Parameter Name=&quot;AlphaSortMask&quot; /&gt;
        ///    &lt;Para [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShaderHelper {
            get {
                return ResourceManager.GetString("ShaderHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] silence {
            get {
                object obj = ResourceManager.GetObject("silence", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Xv2StageDef&gt;
        ///  &lt;Stage idx=&quot;0&quot; ssid=&quot;0&quot;&gt;
        ///    &lt;BASE_DIR value=&quot;data/stage/&quot; /&gt;
        ///    &lt;CODE value=&quot;LBY&quot; /&gt;
        ///    &lt;DIR value=&quot;LBY&quot; /&gt;
        ///    &lt;STR4 value=&quot;LBY&quot; /&gt;
        ///    &lt;EVE value=&quot;template&quot; /&gt;
        ///    &lt;UNK5 value=&quot;0&quot; /&gt;
        ///    &lt;F6 value=&quot;200.0&quot; /&gt;
        ///    &lt;SE value=&quot;&quot; /&gt;
        ///    &lt;BGM_CUE_ID value=&quot;0&quot; /&gt;
        ///    &lt;OVERRIDE_FAR_CLIP value=&quot;0.0&quot; /&gt;
        ///    &lt;LIMIT value=&quot;500.0&quot; /&gt;
        ///    &lt;Gate&gt;
        ///      &lt;NAME value=&quot;&quot; /&gt;
        ///      &lt;TARGET_STAGE_IDX value=&quot;4294967295&quot; /&gt;
        ///      &lt;U_0C value=&quot;0x0&quot; /&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string xv2_stage_def {
            get {
                return ResourceManager.GetString("xv2_stage_def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XV2P_SLOTS_STAGE {
            get {
                object obj = ResourceManager.GetObject("XV2P_SLOTS_STAGE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] XV2P_SLOTS_STAGE_LOCAL {
            get {
                object obj = ResourceManager.GetObject("XV2P_SLOTS_STAGE_LOCAL", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
